import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { dir } from 'i18next';
import { languages } from '../i18n/settings';

const inter = Inter({ subsets: ['latin'] });

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: 'Roberto Saliola | Web Developer',
  description: 'Generated by create next app', //TODO -> add description
};

export default function RootLayout({
  children,
  params: { lng },
}: Readonly<{
  children: React.ReactNode;
  params: { lng: string };
}>) {
  return (
    <html
      lang={lng}
      dir={dir(lng)}
      className="dark scroll-smooth"
    >
      <body className={`${inter.className} flex flex-col h-screen`}>{children}</body>
    </html>
  );
}
